Update Current Code & README Documentation
Adirontech/trek-webapp pull request #21
Opened 2024-02-16 18:55 UTC by BigBass934

- Completed code documentation for all JavaScript & SQL files in the project.
- Re-wrote & Updated the project's main README document to contain full information on setup for developers.

2024-02-19 02:30 UTC, heathermoses approved these changes
lgtm

2024-02-19 03:15 UTC, cpt2162 commented on api/models/userModel.js
>  async function getUserInfo(key) {
the key should be specified as the session key, it clear up ambiguity. Sorry, thats on me.

2024-02-19 03:46 UTC, cpt2162 requested changes
I left one comment, other than that it looks great

2024-02-21 23:10 UTC, cpt2162 approved these changes

2024-02-21 23:10 UTC, merged